#!/usr/bin/env python

import os
import shutil
import sys

base = "README_base.md"
out = "README.md"

if not os.path.exists(base):
    print("Error! Could not find file = " + base)
    sys.exit(-1)


locals2net = [
    ['](_modules/',
    '](https://carltonwin8.github.io/CarND-Vehicle-Detection/_modules/'],
    ['href="_modules/',
    'href="https://carltonwin8.github.io/CarND-Vehicle-Detection/_modules/']
]

with open(base) as f:
    content = f.read()

for local2net in locals2net:
    localStr,  netStr = local2net
    content = content.replace(localStr, netStr)

with open(out,"w") as f:
    f.write(content)
