#!/bin/bash

makeReadme ()
{
	./readme
	grip --export --title="Lane Finding" README_base.md
	if [ -d _build/html ]; then
		mv README_base.html _build/html/index_readme.html
		mv _build/html/index_readme.html _build/html/index.html
		rsync -az test_images/ _build/html/test_images/
		rsync -az output_images/ _build/html/output_images/
	else
		echo _build/html does not exist, so readme not exported
	fi
	echo
	echo README Watch Done
	echo
}

makeReadme
while inotifywait -e close_write README_base.md; do
	makeReadme
done
