#!/bin/bash

watchCode ()
{
	if [ -d rst ]; then
		rm rst/*
	else
		mkdir rst
	fi
	sphinx-apidoc -fo rst src
	mv _build/html/index.html _build/html/index_readme.html
	make html
	mv _build/html/index.html _build/html/index_code.html
	mv _build/html/index_readme.html _build/html/index.html
	cp _config.yml _build/html
	cp .nojekyll _build/html
	echo
	echo Code Watch Done
	echo
}

watchCode
while inotifywait -e close_write src/*.py; do
	watchCode
done
